function outp=lti4o2parallelgc(pm,t)
% outp=lti4oparallelgc(pm,t)
%
%convolution of lti4oparallel2 function and single exponential a la Wang2013
%
%parameterization following paper Supp Info.
%
%Saul Kato
%130905
%


%Gcamp value from Sun, 2013
if length(pm)==7
    taugc=pm(7);
else
    taugc=.4963;
end

tausrise=pm(1);
taufrise=pm(2);
tausfall=pm(3);
tauffall=pm(4);

kasoverkaf=pm(5);
kaspluskaf=pm(6);

kaf=kaspluskaf/(kasoverkaf+1);

kas=kaspluskaf*(kasoverkaf)/(kasoverkaf+1);


% outp=tau_gc*((  (exp(-(t/tau_f_fall)) - exp(-(t/tau_gc))*kaf*tau_f_fall^2*tau_f_rise)/...
%    ( (tau_f_fall - tau_gc)*abs(tau_f_fall - tau_f_rise) ) + ...
%   ((-1 + exp(t*(-1/tau_f_fall - 1/tau_f_rise + 1/tau_gc)))*kaf*tau_f_fall^2*...
%     tau_f_oise^2)/(exp(t/tau_gc)*(-(tau_f_fall*tau_f_rise) + (tau_f_fall + tau_f_rise)*tau_gc)*...
%     abs(tau_f_fall - tau_f_rise)) + ((exp(-(t/tau_gc)) - exp(-(t/tau_s_fall)))*kas*...
%     tau_s_fall^2*tau_s_rise)/((tau_gc - tau_s_fall)*abs(tau_s_fall - tau_s_rise)) - ...
%   ((exp(-(t/tau_gc)) - exp(-((t*(tau_s_fall + tau_s_rise))/(tau_s_fall*tau_s_rise))))*kas*...
%     tau_s_fall^2*tau_s_rise^2)/((-(tau_s_fall*tau_s_rise) + tau_gc*(tau_s_fall + tau_s_rise))*...
%     abs(tau_s_fall - tau_s_rise) ));


% outp=taugc*(((exp(-(t/tauffall)) - exp(-(t/taugc)))*kaf*tauffall^2*taufrise)/ ...
%    ((tauffall - taugc)*abs(tauffall - taufrise)) +  ...
%   ((-1 + exp((-tauffall^(-1) - taufrise^(-1) + taugc^(-1))*t))*kaf*tauffall^2* ...
%     taufrise^2)./(exp(t/taugc)*(-(tauffall*taufrise) +  ...
%      (tauffall + taufrise)*taugc)*abs(tauffall - taufrise)) +  ...
%   ((exp(-(t/taugc)) - exp(-(t/tausfall)))*kas*tausfall^2*tausrise)/ ...
%    ((taugc - tausfall)*abs(tausfall - tausrise)) -  ...
%   ((exp(-(t/taugc)) - exp(-(((tausfall + tausrise)*t)/(tausfall*tausrise))))*kas* ...
%     tausfall^2*tausrise^2)/((-(tausfall*tausrise) +  ...
%      taugc*(tausfall + tausrise))*abs(tausfall - tausrise)));
 
outp= taugc*(((exp(-(t/tauffall)) - exp(-(t/taugc)))*kaf*tauffall^2*taufrise)/ ...
   ((tauffall - taugc)*abs(tauffall - taufrise)) +  ...
  ((-1 + exp((-tauffall^(-1) - taufrise^(-1) + taugc^(-1))*t))*kaf*tauffall^2* ...
    taufrise^2)./(exp(t/taugc)*(-(tauffall*taufrise) +  ...
     (tauffall + taufrise)*taugc)*abs(tauffall - taufrise)) -  ...
  ((exp(-(t/taugc)) - exp(-(t/tausfall)))*kas*tausfall^2*tausrise)/ ...
   ((taugc - tausfall)*abs(tausfall - tausrise)) +  ...
  ((exp(-(t/taugc)) - exp(-(((tausfall + tausrise)*t)/(tausfall*tausrise))))*kas* ...
    tausfall^2*tausrise^2)/((-(tausfall*tausrise) +  ...
     taugc*(tausfall + tausrise))*abs(tausfall - tausrise)));


